# Generated by Django 4.0.4 on 2022-04-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='source',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
